# Config file for automatic testing at travis-ci.org
# This file will be regenerated if you run travis_pypi_setup.py

language: python
python: 3.7

env:
  - TOXENV=py37
  - TOXENV=py36
  - TOXENV=py35
  - TOXENV=pypy

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -U tox

# command to run tests, e.g. python setup.py test
script: tox -e ${TOXENV}

# After you create the Github repo and add it to Travis, run the
# travis_pypi_setup.py script to finish PyPI deployment setup
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: opendisplays
  password:
    secure: PLEASE_REPLACE_ME
  on:
    tags: true
    repo: opendisplays/yarely
    condition: $TOXENV == py37
